### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lucassouza252**

### CODE REVIEW

**Comment by vlandham** [comment]
Hi @lucassouza252 . thanks for the contribution. 

Munging is in fact a term used in the data manipulation world. Here is a wikipedia link:

https://en.wikipedia.org/wiki/Mung_(computer_term)

I'm not sure the definition of "minging". The one I'm finding means "foul breath"

https://en.oxforddictionaries.com/definition/minging

But perhaps your suggestion points to the need to use less jargon-y words in an introductory text like this?

thanks,
Jim

**Comment by lucassouza252** [comment]
Sorry, I did not know that term, and I talked to friends, they did not know it either.
I know This expression: http://www.anderson.ucla.edu/faculty/jason.frand/teacher/technologies/palace/datamining.htm

**Comment by lucassouza252** [comment]
I know This expression: http://www.anderson.ucla.edu/faculty/jason.frand/teacher/technologies/palace/datamining.htm

**Comment by vlandham** [comment]
yep. i think data mining is a slightly different angle. But I have created #37 to improve this language. I think for this specific issue, i will remove 'munging' and replace it with a more general, common term. I'd like to go through the site to ensure the language is consistently accessible. 

Thanks very much!

**Pull request closed without merging**
